### ISSUE TITLE
geom_sf in ggplot?

### ISSUE THREAD

**Issue by sacool** [robyngit/cartographr#2]
When plotting the data, I get the following error: 
`Error in geom_sf(data = all_roads_sfcollection$osm_lines, aes(color = highway)) :
  could not find function "geom_sf"`
I thought that this was maybe because I had an older version of ggplot, but I updated it, and still get the same error. 
`> packageVersion("ggplot2")
[1] ‘2.2.1’`

**Comment by robyngit** [comment]
At the moment, you must to use the development version of `ggplot2` - `ggplot2 2.2.1.9000`

Try:
```
install.packages("devtools")
devtools::install_github("tidyverse/ggplot2")
```
Commented code to clarify.
